version: '3.8'

services:
  db:
    image: mongo:6.0
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: my_backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=mongodb://db:27017
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: my_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
